export interface QuizQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
}

const ALL_QUESTIONS: QuizQuestion[] = [
  { id: 1, question: "O que é Phishing?", options: ["Um tipo de peixe", "Técnica de engenharia social para roubar dados", "Um firewall", "Um protocolo de rede"], correctAnswer: 1, explanation: "Phishing é uma técnica onde atacantes se passam por entidades confiáveis para roubar informações sensíveis." },
  { id: 2, question: "O que significa MFA?", options: ["Multi-Function Access", "Multiple File Archive", "Multi-Factor Authentication", "Main Frame Access"], correctAnswer: 2, explanation: "Multi-Factor Authentication (Autenticação Multifator) exige duas ou mais provas de identidade para acessar uma conta." },
  { id: 3, question: "Qual porta padrão é usada pelo protocolo SSH?", options: ["21", "22", "80", "443"], correctAnswer: 1, explanation: "O protocolo SSH (Secure Shell) utiliza por padrão a porta 22." },
  { id: 4, question: "O que é um ataque de Força Bruta?", options: ["Destruição física do servidor", "Tentar todas as senhas possíveis até acertar", "Bloquear o acesso à rede", "Roubar o disco rígido"], correctAnswer: 1, explanation: "A força bruta consiste em testar sistematicamente combinações de senhas até encontrar a correta." },
  { id: 5, question: "Qual é a principal função de um Firewall?", options: ["Acelerar a internet", "Fazer backup de arquivos", "Filtrar tráfego de rede e bloquear acessos não autorizados", "Remover vírus do computador"], correctAnswer: 2, explanation: "Firewalls monitoram e controlam o tráfego de rede baseado em regras de segurança pré-definidas." },
  { id: 6, question: "O que é SQL Injection?", options: ["Injetar código malicioso em banco de dados", "Um tipo de vacina", "Um cabo de rede", "Uma técnica de criptografia"], correctAnswer: 0, explanation: "SQL Injection é uma falha que permite a execução de comandos SQL maliciosos no banco de dados." },
  { id: 7, question: "O que significa DDoS?", options: ["Data Distribution OS", "Distributed Denial of Service", "Direct Data on System", "Digital Domain of Security"], correctAnswer: 1, explanation: "DDoS é um ataque que visa sobrecarregar um serviço ou rede enviando uma quantidade massiva de tráfego de múltiplas fontes." },
  { id: 8, question: "Qual a finalidade de um ataque Ransomware?", options: ["Otimizar o PC", "Criptografar dados e exigir resgate", "Aumentar a velocidade da rede", "Proteger contra vírus"], correctAnswer: 1, explanation: "Ransomware criptografa os arquivos do usuário e os cibercriminosos exigem pagamento (resgate) para liberar a chave." },
  { id: 9, question: "O que é um ataque Man-in-the-Middle (MitM)?", options: ["Um jogo de xadrez", "Um antivírus", "Interceptação e possível alteração de comunicação entre duas partes", "Um erro de servidor"], correctAnswer: 2, explanation: "No MitM, o atacante se posiciona entre as duas partes que se comunicam para interceptar ou alterar os dados trafegados." },
  { id: 10, question: "Qual destes é um protocolo seguro para navegação web?", options: ["HTTP", "FTP", "Telnet", "HTTPS"], correctAnswer: 3, explanation: "HTTPS usa criptografia TLS/SSL para proteger a comunicação entre o navegador e o servidor web." },
  { id: 11, question: "O que significa VPN?", options: ["Virtual Private Network", "Visual Processing Node", "Very Personal Name", "Virtual Public Network"], correctAnswer: 0, explanation: "Virtual Private Network cria um túnel seguro e criptografado sobre uma rede pública, como a internet." },
  { id: 12, question: "Qual é a porta padrão para o protocolo HTTPS?", options: ["80", "443", "25", "53"], correctAnswer: 1, explanation: "A porta padrão para tráfego seguro (HTTPS) é a 443." },
  { id: 13, question: "O que é Engenharia Social no contexto de segurança?", options: ["Construção de pontes de rede", "Uso de persuasão para manipular pessoas a revelar informações", "Programação de inteligência artificial", "Criar comunidades online"], correctAnswer: 1, explanation: "Engenharia Social explora a falibilidade humana através da manipulação psicológica." },
  { id: 14, question: "O que significa CVE?", options: ["Computer Virus Eradicator", "Common Vulnerabilities and Exposures", "Cyber Virtual Environment", "Central Volume Execution"], correctAnswer: 1, explanation: "CVE é um dicionário que provê nomes e identificadores para vulnerabilidades de segurança conhecidas publicamente." },
  { id: 15, question: "O que é Hashing?", options: ["Esconder arquivos", "Um tipo de droga", "Converter dados em uma string de tamanho fixo para verificar integridade", "Comprimir imagens"], correctAnswer: 2, explanation: "Hashing é usado para gerar uma assinatura única (hash) de um dado, útil para verificar senhas e a integridade de arquivos." },
  { id: 16, question: "Qual ferramenta é comumente usada para varredura de portas?", options: ["Photoshop", "Nmap", "Word", "Excel"], correctAnswer: 1, explanation: "O Nmap (Network Mapper) é a ferramenta open-source mais popular para exploração de rede e auditoria de segurança." },
  { id: 17, question: "O que é um ataque de Zero-Day?", options: ["Um ataque que ocorre à meia-noite", "Ataque que explora uma vulnerabilidade recém-descoberta, sem correção disponível", "Um vírus que apaga todos os dados no dia zero", "Um ataque sem sucesso"], correctAnswer: 1, explanation: "Ataques Zero-Day exploram falhas desconhecidas pelo fornecedor do software, logo, ainda sem patch de correção." },
  { id: 18, question: "Qual a principal diferença entre IDS e IPS?", options: ["Nenhuma", "IDS monitora, IPS monitora e bloqueia ativamente", "IDS é hardware, IPS é software", "IPS é mais antigo"], correctAnswer: 1, explanation: "Intrusion Detection System (IDS) apenas alerta, enquanto Intrusion Prevention System (IPS) também toma ações para bloquear a ameaza." },
  { id: 19, question: "O que é um rootkit?", options: ["Um kit de ferramentas de rede", "Malware projetado para esconder a existência de processos ou programas", "Um tipo de roteador", "Um sistema operacional"], correctAnswer: 1, explanation: "Rootkits modificam o sistema operacional para se ocultar dos softwares antivírus e do próprio administrador." },
  { id: 20, question: "Qual desses é um exemplo de autenticação biométrica?", options: ["Senha", "Token SMS", "Impressão digital", "Cartão magnético"], correctAnswer: 2, explanation: "A biometria utiliza características físicas únicas, como impressões digitais, retina ou reconhecimento facial." },
  { id: 21, question: "O que é um ataque de Dicionário?", options: ["Usar um dicionário de idiomas para traduzir", "Tentar senhas comuns baseadas em uma lista de palavras", "Atacar usando livros físicos", "Criar novas palavras-passe"], correctAnswer: 1, explanation: "Semelhante à força bruta, mas usa uma lista pré-definida de palavras prováveis, sendo mais rápido do que testar todas as combinações de caracteres." },
  { id: 22, question: "O que é um cavalo de Troia (Trojan)?", options: ["Um vírus que se replica pela rede", "Um cavalo de madeira", "Um software legítimo na aparência, mas que contém código malicioso", "Um tipo de firewall"], correctAnswer: 2, explanation: "Trojans enganam os usuários ao parecerem úteis ou inofensivos, mas escondem funcionalidades destrutivas." },
  { id: 23, question: "Qual é o principal objetivo da criptografia?", options: ["Proteger a confidencialidade e integridade dos dados", "Aumentar o tamanho do arquivo", "Compactar os dados", "Tornar a internet mais rápida"], correctAnswer: 0, explanation: "A criptografia transforma dados legíveis em um formato ininteligível para proteger informações." },
  { id: 24, question: "O que significa XSS?", options: ["XML System Server", "Cross-Site Scripting", "Extra Secure Socket", "Xtreme Security System"], correctAnswer: 1, explanation: "Cross-Site Scripting é uma vulnerabilidade web que permite injetar scripts maliciosos em páginas visualizadas por outros usuários." },
  { id: 25, question: "O que é uma Botnet?", options: ["Uma rede social de robôs", "Uma rede de computadores infectados controlados por um atacante", "Um antivírus", "Uma ferramenta de programação"], correctAnswer: 1, explanation: "Botnets são usadas frequentemente para realizar ataques DDoS, enviar spam ou minerar criptomoedas em massa." },
  { id: 26, question: "O que é Engenharia Social Reversa?", options: ["Fazer a vítima procurar o atacante pedindo ajuda", "Ler o código ao contrário", "Devolver o dinheiro roubado", "Criar um ataque sem vírus"], correctAnswer: 0, explanation: "Na engenharia social reversa, o atacante cria um cenário onde a própria vítima acredita precisar da ajuda dele." },
  { id: 27, question: "O que é um ataque de Spoofing?", options: ["Jogar online com cheats", "Falsificar a identidade para parecer uma fonte confiável", "Desligar os servidores", "Fazer backup de arquivos"], correctAnswer: 1, explanation: "Pode ocorrer com IP, e-mail ou DNS, fazendo a vítima acreditar que está se comunicando com uma entidade legítima." },
  { id: 28, question: "O que é o princípio do Menor Privilégio?", options: ["Dar acesso root para todos", "Dar aos usuários apenas os acessos estritamente necessários para seu trabalho", "Não usar senhas", "Sempre comprar o software mais barato"], correctAnswer: 1, explanation: "É um conceito chave em segurança que minimiza a superfície de ataque ao restringir permissões desnecessárias." },
  { id: 29, question: "O que é uma ameaça APT?", options: ["Advanced Persistent Threat", "Anti-Phishing Tool", "Automated Proxy Tracker", "Ataque Para Teste"], correctAnswer: 0, explanation: "APT refere-se a ataques prolongados e direcionados, frequentemente conduzidos por grupos patrocinados por estados-nação." },
  { id: 30, question: "O que é um Honeypot?", options: ["Um pote de mel", "Um sistema intencionalmente vulnerável para atrair e estudar atacantes", "Um roteador super potente", "Uma técnica de criptografia avançada"], correctAnswer: 1, explanation: "Honeypots atuam como iscas para desviar ataques dos sistemas reais e coletar inteligência sobre as táticas dos invasores." },
  { id: 31, question: "O que o protocolo DNS faz?", options: ["Criptografa senhas", "Traduz nomes de domínio legíveis para endereços IP", "Bloqueia vírus", "Limpa o cache do navegador"], correctAnswer: 1, explanation: "O Domain Name System atua como a lista telefônica da internet, traduzindo URLs para IPs." },
  { id: 32, question: "O que é um Keylogger?", options: ["Um cadeado digital", "Um software ou hardware que registra tudo o que é digitado no teclado", "Uma ferramenta para criar chaves SSH", "Um gerador de senhas"], correctAnswer: 1, explanation: "Keyloggers são frequentemente usados para roubar senhas e credenciais interceptando as teclas digitadas pela vítima." },
  { id: 33, question: "O que é Typosquatting?", options: ["Escrever muito rápido", "Registrar domínios com erros de digitação comuns de sites populares", "Hackear teclados virtuais", "Um erro de programação"], correctAnswer: 1, explanation: "Atacantes registram sites como 'gogle.com' para enganar usuários que digitam URLs incorretamente e distribuir malware ou phishing." },
  { id: 34, question: "Qual a diferença entre HTTP e HTTPS?", options: ["HTTP é mais rápido", "HTTPS criptografa a comunicação, HTTP não", "HTTPS é só para bancos", "HTTP é pago"], correctAnswer: 1, explanation: "HTTPS usa a camada de segurança TLS/SSL, impedindo que os dados sejam lidos em texto plano caso sejam interceptados." },
  { id: 35, question: "O que é Payload em segurança da informação?", options: ["Um caminhão de carga", "O custo do ataque", "A parte do malware que realiza a ação maliciosa pretendida", "Um antivírus"], correctAnswer: 2, explanation: "O payload é o código que executa o dano, como a rotina que apaga arquivos ou o script de criptografia de um ransomware." }
];

export const generateQuiz = (count: number = 5): QuizQuestion[] => {
  const shuffled = [...ALL_QUESTIONS].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};
